module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_readonly: 0
  config_split: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  ctools_entity_mask: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  easy_install: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  geolocation: 0
  help: 0
  hms_field: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  kint: 0
  language: 0
  link: 0
  linkit: 0
  media: 0
  media_entity_browser: 0
  memcache: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  migrate: 0
  migrate_drupal: 0
  migrate_nidirect_file: 0
  migrate_nidirect_global: 0
  migrate_nidirect_node_application: 0
  migrate_nidirect_node_article: 0
  migrate_nidirect_node_page: 0
  migrate_nidirect_node_publication: 0
  migrate_nidirect_node_recipe: 0
  migrate_nidirect_taxo: 0
  migrate_nidirect_user: 0
  migrate_nidirect_utils: 0
  migrate_plus: 0
  migrate_tools: 0
  nidirect_breadcrumbs: 0
  nidirect_cold_weather_payments: 0
  nidirect_common: 0
  nidirect_contacts: 0
  nidirect_errorpages: 0
  nidirect_gp: 0
  nidirect_workflow: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_inline_entity_form: 0
  path: 0
  responsive_image: 0
  rest: 0
  restui: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  shs: 0
  simplei: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  traffic_light_rating: 0
  twig_extensions: 0
  ultimate_cron: 0
  user: 0
  views_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  nicsdru_origins_theme: 0
  nicsdru_nidirect_theme: 0
  adminimal_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
